// Realistic seed data modeled directly on kanbots' real schema.
// Issue / AgentRun / AgentEvent shapes mirror packages/web/src/types.ts.

window.KB_DATA = (() => {
  const NOW = Date.now();
  const ago = (mins) => new Date(NOW - mins * 60_000).toISOString();

  const users = {
    you:    { login: 'jess',     avatarUrl: null, color: 'oklch(0.72 0.16 45)' },
    raj:    { login: 'raj',      avatarUrl: null, color: 'oklch(0.70 0.14 200)' },
    mira:   { login: 'mira',     avatarUrl: null, color: 'oklch(0.74 0.13 320)' },
    leo:    { login: 'leo',      avatarUrl: null, color: 'oklch(0.78 0.14 130)' },
  };

  // Issues span every column + every agent state. Status keys match codebase.
  const issues = [
    {
      number: 412,
      title: 'Migrate auth flow to passkeys (WebAuthn)',
      body: 'Replace password+TOTP login with passkey-first onboarding. Keep magic-link as fallback for 90 days.',
      state: 'open',
      labels: ['status:in-progress', 'area:auth', 'priority:p1'],
      assignees: ['raj'],
      user: users.you,
      createdAt: ago(60 * 36),
      updatedAt: ago(3),
      isPullRequest: false,
      status: 'inProgress',
      agent: 'running',
      // extended (design-only)
      branch: 'kb/412-passkey-onboarding',
      filesChanged: 14,
      additions: 612, deletions: 187,
      tokens: { in: 184_300, out: 41_200 },
      progress: 0.62,
      currentTool: 'Edit',
      currentFile: 'apps/web/src/auth/passkey/register.ts',
      elapsedSec: 1840,
      checks: { tests: 'running', typecheck: 'pass', lint: 'pass' },
      runId: 7821,
      avatar: '◉',
      tag: 'IMPL',
    },
    {
      number: 408,
      title: 'Streaming SSE endpoint drops mid-message on Cloudflare',
      body: 'Reports of agent ticker freezing after ~30s on Workers. Need to add heartbeat frames and verify nginx buffering off.',
      state: 'open',
      labels: ['status:in-progress', 'area:api', 'priority:p0', 'bug'],
      assignees: ['mira'],
      user: users.raj,
      createdAt: ago(60 * 12),
      updatedAt: ago(1),
      isPullRequest: false,
      status: 'inProgress',
      agent: 'awaiting',
      branch: 'kb/408-sse-heartbeat',
      filesChanged: 4,
      additions: 89, deletions: 22,
      tokens: { in: 64_100, out: 12_900 },
      progress: 0.48,
      currentTool: 'Bash',
      currentFile: 'packages/api/src/agent-runs/stream.ts',
      elapsedSec: 412,
      checks: { tests: 'fail', typecheck: 'pass', lint: 'pass' },
      runId: 7824,
      decision: {
        question: 'The current frame buffer is 8KB. Bump to 32KB or send keepalives every 15s?',
        options: [
          { value: 'buffer', label: 'Larger buffer (32KB)' },
          { value: 'keepalive', label: 'Heartbeats every 15s' },
          { value: 'both', label: 'Both' },
        ],
      },
      avatar: '◈',
      tag: 'BUG',
    },
    {
      number: 415,
      title: 'Add /spec command to refine task before implementation',
      body: 'Allow agent to converse with the user to flesh out requirements, then write a spec.md to the worktree before any code is touched.',
      state: 'open',
      labels: ['status:in-progress', 'area:dispatcher', 'feature'],
      assignees: ['leo'],
      user: users.you,
      createdAt: ago(60 * 4),
      updatedAt: ago(0.3),
      isPullRequest: false,
      status: 'inProgress',
      agent: 'running',
      branch: 'kb/415-spec-command',
      filesChanged: 6,
      additions: 240, deletions: 14,
      tokens: { in: 92_400, out: 28_100 },
      progress: 0.35,
      currentTool: 'Read',
      currentFile: 'packages/dispatcher/src/composer.ts',
      elapsedSec: 240,
      checks: { tests: '—', typecheck: 'running', lint: '—' },
      runId: 7826,
      avatar: '◊',
      tag: 'FEAT',
    },

    // REVIEW
    {
      number: 401,
      title: 'Worktree cleanup on agent crash leaves dangling branches',
      body: 'When `claude -p` exits non-zero, the worktree is removed but the branch ref hangs around forever. Add a janitor.',
      state: 'open',
      labels: ['status:review', 'area:dispatcher', 'bug'],
      assignees: ['raj'],
      user: users.mira,
      createdAt: ago(60 * 80),
      updatedAt: ago(15),
      isPullRequest: true,
      status: 'review',
      agent: 'review',
      branch: 'kb/401-worktree-janitor',
      filesChanged: 3,
      additions: 124, deletions: 41,
      tokens: { in: 41_200, out: 9_800 },
      progress: 1,
      checks: { tests: 'pass', typecheck: 'pass', lint: 'pass' },
      runId: 7790,
      avatar: '◎',
      tag: 'PR',
    },
    {
      number: 403,
      title: 'Dark mode tokens for agent ticker',
      body: 'Ticker uses hardcoded #fafbfc. Move to CSS vars and add a slate scheme.',
      state: 'open',
      labels: ['status:review', 'area:web', 'design'],
      assignees: ['mira'],
      user: users.you,
      createdAt: ago(60 * 22),
      updatedAt: ago(45),
      isPullRequest: true,
      status: 'review',
      agent: 'review',
      branch: 'kb/403-ticker-dark',
      filesChanged: 7,
      additions: 198, deletions: 96,
      tokens: { in: 28_800, out: 7_200 },
      progress: 1,
      checks: { tests: 'pass', typecheck: 'pass', lint: 'pass' },
      runId: 7811,
      avatar: '◐',
      tag: 'PR',
    },

    // TODO
    {
      number: 419,
      title: 'Decision queue: aggregate awaiting_input prompts across runs',
      body: 'Build a global tray that surfaces every pending decision card from every active agent run, with a one-key resolve.',
      state: 'open',
      labels: ['status:todo', 'area:web', 'feature'],
      assignees: [],
      user: users.you,
      createdAt: ago(60 * 6),
      updatedAt: ago(60),
      isPullRequest: false,
      status: 'todo',
      agent: 'idle',
      avatar: '○',
      tag: 'FEAT',
    },
    {
      number: 420,
      title: 'MCP: expose worktree filesystem as a resource',
      body: 'Let external tools mount the agent worktree read-only via MCP.',
      state: 'open',
      labels: ['status:todo', 'area:mcp'],
      assignees: ['leo'],
      user: users.raj,
      createdAt: ago(60 * 8),
      updatedAt: ago(120),
      isPullRequest: false,
      status: 'todo',
      agent: 'queued',
      avatar: '○',
      tag: 'FEAT',
    },
    {
      number: 421,
      title: 'Replace local-store ULID with snowflake for sortable IDs',
      body: 'Migration plan needed; affects all foreign keys.',
      state: 'open',
      labels: ['status:todo', 'area:local-store', 'priority:p2'],
      assignees: [],
      user: users.you,
      createdAt: ago(60 * 28),
      updatedAt: ago(180),
      isPullRequest: false,
      status: 'todo',
      agent: 'idle',
      avatar: '○',
      tag: 'CHORE',
    },

    // BACKLOG
    {
      number: 430,
      title: 'Token-usage budget alerts per workspace',
      body: '',
      state: 'open',
      labels: ['status:backlog', 'area:api'],
      assignees: [],
      user: users.you,
      createdAt: ago(60 * 50),
      updatedAt: ago(60 * 50),
      isPullRequest: false,
      status: 'backlog',
      agent: 'idle',
      avatar: '·',
      tag: 'FEAT',
    },
    {
      number: 431,
      title: 'Allow agent to spawn sub-agents (fan-out/fan-in)',
      body: '',
      state: 'open',
      labels: ['status:backlog', 'area:dispatcher', 'priority:p2'],
      assignees: [],
      user: users.you,
      createdAt: ago(60 * 80),
      updatedAt: ago(60 * 80),
      isPullRequest: false,
      status: 'backlog',
      agent: 'idle',
      avatar: '·',
      tag: 'FEAT',
    },
    {
      number: 432,
      title: 'Voice-to-issue: dictate, agent drafts, you confirm',
      body: '',
      state: 'open',
      labels: ['status:backlog', 'area:desktop', 'feature'],
      assignees: [],
      user: users.you,
      createdAt: ago(60 * 90),
      updatedAt: ago(60 * 90),
      isPullRequest: false,
      status: 'backlog',
      agent: 'idle',
      avatar: '·',
      tag: 'FEAT',
    },

    // INBOX
    {
      number: 436,
      title: 'crash on switch workspace if SSE stream still attached',
      body: 'Repro: open issue #408, watch ticker, click Switch workspace.',
      state: 'open',
      labels: [],
      assignees: [],
      user: users.mira,
      createdAt: ago(20),
      updatedAt: ago(20),
      isPullRequest: false,
      status: null,
      agent: 'idle',
      avatar: '⌘',
      tag: 'BUG',
    },

    // DONE
    {
      number: 388,
      title: 'Stream parser: handle interleaved tool_result frames',
      body: '',
      state: 'closed',
      labels: ['status:done', 'area:dispatcher'],
      assignees: ['raj'],
      user: users.raj,
      createdAt: ago(60 * 200),
      updatedAt: ago(60 * 6),
      isPullRequest: true,
      status: 'done',
      agent: 'idle',
      branch: 'kb/388-interleaved',
      avatar: '✓',
      tag: 'PR',
    },
    {
      number: 392,
      title: 'Persist composer drafts per issue',
      body: '',
      state: 'closed',
      labels: ['status:done', 'area:web'],
      assignees: ['mira'],
      user: users.mira,
      createdAt: ago(60 * 180),
      updatedAt: ago(60 * 20),
      isPullRequest: true,
      status: 'done',
      agent: 'idle',
      avatar: '✓',
      tag: 'PR',
    },
  ];

  // Live ticker events for the focused issue (#412)
  const tickerEvents = [
    { id: 1, type: 'text',        text: "I'll start by reading the current auth flow to understand the password + TOTP path before swapping in passkeys." },
    { id: 2, type: 'tool_use',    name: 'Read',  input: 'apps/web/src/auth/login.ts' },
    { id: 3, type: 'tool_result', summary: '218 lines · 6 imports · uses bcrypt + speakeasy' },
    { id: 4, type: 'tool_use',    name: 'Glob',  input: '**/*.{ts,tsx} containing "password"' },
    { id: 5, type: 'tool_result', summary: '34 matches across 12 files' },
    { id: 6, type: 'text',        text: 'There are three call sites that need to be updated: the login page, the API handler, and the session middleware. Starting with the API handler since the others depend on its return shape.' },
    { id: 7, type: 'tool_use',    name: 'Edit',  input: 'packages/api/src/auth/login.handler.ts' },
    { id: 8, type: 'tool_result', summary: '+38 −12 lines' },
    { id: 9, type: 'tool_use',    name: 'Edit',  input: 'apps/web/src/auth/login.ts' },
    { id: 10, type: 'tool_result', summary: '+62 −41 lines' },
    { id: 11, type: 'tool_use',    name: 'Bash', input: 'pnpm typecheck' },
    { id: 12, type: 'tool_result', summary: 'tsc — no errors · 4.2s' },
    { id: 13, type: 'text',        text: 'Now adding the WebAuthn registration ceremony. I need to decide whether to use SimpleWebAuthn or build the ArrayBuffer plumbing manually.' },
    { id: 14, type: 'tool_use',    name: 'Edit', input: 'apps/web/src/auth/passkey/register.ts', live: true },
  ];

  // Diff for the docked preview
  const diff = {
    base: 'main',
    branch: 'kb/412-passkey-onboarding',
    files: [
      {
        path: 'apps/web/src/auth/passkey/register.ts',
        status: 'added',
        hunks: [
          { meta: '@@ -0,0 +1,42 @@', lines: [
            { k: 'add', t: "import { startRegistration } from '@simplewebauthn/browser';" },
            { k: 'add', t: "import { api } from '../../api';" },
            { k: 'add', t: '' },
            { k: 'add', t: 'export async function registerPasskey(userId: string) {' },
            { k: 'add', t: '  const opts = await api.passkeys.beginRegistration({ userId });' },
            { k: 'add', t: '  const att  = await startRegistration(opts);' },
            { k: 'add', t: '  return api.passkeys.finishRegistration({ userId, att });' },
            { k: 'add', t: '}' },
          ]},
        ],
      },
      {
        path: 'apps/web/src/auth/login.ts',
        status: 'modified',
        hunks: [
          { meta: '@@ -42,7 +42,12 @@ export async function loginWithPassword(', lines: [
            { k: 'ctx', t: '  const session = await api.session.create({' },
            { k: 'del', t: '    method: "password",' },
            { k: 'del', t: '    password,' },
            { k: 'add', t: '    method: hasPasskey ? "passkey" : "password",' },
            { k: 'add', t: '    passkey: hasPasskey ? attestation : undefined,' },
            { k: 'add', t: '    password: hasPasskey ? undefined : password,' },
            { k: 'ctx', t: '    totp,' },
            { k: 'ctx', t: '  });' },
          ]},
        ],
      },
    ],
  };

  // Decision queue (across runs)
  const decisions = [
    {
      runId: 7824,
      issueNumber: 408,
      issueTitle: 'Streaming SSE endpoint drops mid-message on Cloudflare',
      question: 'Bump the frame buffer to 32KB or send keepalives every 15s?',
      options: [
        { value: 'buffer', label: 'Larger buffer' },
        { value: 'keepalive', label: 'Heartbeats' },
        { value: 'both', label: 'Both' },
      ],
      ageSec: 92,
    },
    {
      runId: 7826,
      issueNumber: 415,
      issueTitle: 'Add /spec command to refine task',
      question: 'Should /spec write to spec.md in the repo root or in .kanbots/specs/?',
      options: [
        { value: 'root', label: 'Repo root' },
        { value: 'kanbots', label: '.kanbots/specs/' },
      ],
      ageSec: 14,
    },
  ];

  // ONE workspace ("Anthropic stack"), multiple folders inside it.
  const workspace = {
    id: 'anthropic-stack',
    name: 'Anthropic stack',
    activeAgents: 4,
  };
  const folders = [
    { id: 'kanbots',  name: 'kanbots',      path: '~/code/kanbots',      branch: 'main',  activeAgents: 3, current: true,  issues: 12 },
    { id: 'parser',   name: 'sigil-parser', path: '~/code/sigil-parser', branch: 'next',  activeAgents: 0, current: false, issues: 4 },
    { id: 'studio',   name: 'studio.app',   path: '~/code/studio',       branch: 'main',  activeAgents: 1, current: false, issues: 7 },
    { id: 'site',     name: 'jess.dev',     path: '~/code/jess.dev',     branch: 'main',  activeAgents: 0, current: false, issues: 2 },
  ];

  return { users, issues, tickerEvents, diff, decisions, workspace, folders };
})();
