export const PACKAGE_NAME = '@kanbots/api';

export {
  createSupervisor,
  RateLimitedError,
  type AgentSupervisor,
  type CooldownListener,
  type CooldownState,
  type CreateSupervisorOptions,
  type ResumeRunInput,
  type StartRunInput,
} from './agent-runs/supervisor.js';
export {
  createAutopilotManager,
  type AutopilotManager,
  type AutopilotManagerOpts,
  type AutopilotRepoConfig,
  type StartAutopilotInput,
  type StartAutopilotResult,
} from './autopilot/orchestrator.js';
export {
  reconcileIssueLabels,
  type ReconcileLabelsResult,
} from './workspace-reconcile.js';
export {
  bootstrapWorkspace,
  type WorkspaceBootstrapResult,
} from './workspace-bootstrap.js';

export {
  createHandlers,
  type CreateHandlersOptions,
  type HandlerDeps,
  type Handlers,
  type SentryAnalyzerFn,
  type SentryRuntime,
  type SubscriptionRegistry,
} from './handlers/index.js';
export type {
  AgentCheck,
  AgentEvent,
  AgentEventType,
  AgentKey,
  AgentRun,
  AgentRunEventPayload,
  AgentRunStatus,
  AutopilotCheckCommand,
  AutopilotChildEntry,
  AutopilotChildKind,
  AutopilotChildStatus,
  AutopilotConfig,
  AutopilotEffort,
  AutopilotKind,
  AutopilotPersonaSnapshot,
  AutopilotSession,
  AutopilotStatus,
  BridgeChannels,
  Card,
  CardStatus,
  CardType,
  ChannelArgs,
  ChannelName,
  ChannelResult,
  CheckKind,
  Comment,
  Config,
  CooldownStatePayload,
  CreateIssueInput,
  DecisionPayload,
  DecoratedIssue,
  DiffFile,
  DiffFileStatus,
  DiffPayload,
  DispatchResult,
  DraftedIssue,
  DraftIssueFn,
  DraftIssueInput,
  SuggestFeatureBacklogEntry,
  SuggestFeatureEntryStatus,
  SuggestFeatureFn,
  SuggestFeatureInput,
  EventSubscribeResult,
  ForkRunResult,
  Issue,
  IssueActiveRunPayload,
  IssueDetail,
  Message,
  PendingDecisionPayload,
  PostMessageResult,
  PreviewState,
  PreviewStatePayload,
  ResolveCardResult,
  Role,
  RunStatsResult,
  SentryAnalyzerInput,
  SentryConfigInput,
  SentryConfigPayload,
  SentryImportStatus,
  SentryMetaPayload,
  SentrySuggestion,
  SentrySuggestionCategory,
  SentrySuggestionConfidence,
  SentrySuggestionVerdict,
  SentrySyncResult,
  SentryTestConnectionResult,
  SplitResult,
  StatusKey,
  ThreadPayload,
  UpdateIssuePatch,
  UploadAttachmentResult,
  Workspace,
  WorkspaceBudgets,
  WorkspaceFolderPayload,
} from './bridge.js';
